version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    volumes:
      - db:/var/lib/postgresql/data


  redis:
    image: redis:latest

    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81



  api:
    build: .
    command: >
      sh -c "alembic revision --autogenerate -m 'first' &&
             alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app

    ports:
      - "8000:8000"

    environment:

      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=api
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

      - DATABASE_URL=${DATABASE_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - APP_SECRET_STRING=${APP_SECRET_STRING}
      - DOMAIN=${DOMAIN}
      - API_AUDIENCE=${API_AUDIENCE}
      - ISSUER=${ISSUER}
      - ALGORITHMS=${ALGORITHMS}


    depends_on:
      - db
      - redis

volumes:

    db:
      driver: local
