version: "3"

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api

  redis:
    image: redis:latest

    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81



  api:
    build: .
    command: >
      sh -c "alembic revision --autogenerate -m 'first' &&
             alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app

    ports:
      - "8000:8000"

    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=api
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    depends_on:
      - db
      - redis