"""fifth

Revision ID: 22fa3479a9ea
Revises: 4f328b07c002
Create Date: 2022-10-12 15:01:07.152925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fa3479a9ea'
down_revision = '4f328b07c002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
