"""first

Revision ID: 2f71b1180bc9
Revises: 79743341a500
Create Date: 2022-10-12 21:48:12.084840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f71b1180bc9"
down_revision = "79743341a500"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
