"""third

Revision ID: 494a1ab4fb5b
Revises: 39063f677808
Create Date: 2022-10-12 14:41:37.772799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "494a1ab4fb5b"
down_revision = "39063f677808"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
