name: Ci-CD-pipeline-TO-AWSELASTICBEANSTALKS
env:
  S3_BUCKET_NAME : "medduzen-internship-packages"
  EB_APLICATION_NAME : "FastApi-Meduzzen"
  EB_ENV_NAME: "Fastapimeduzzen-env"
  DEPLOY_PACKAGE_NAME: "FastApi-Meduzzen_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-west-1"


on:
  push:
    branches:
      - develop

jobs:
  ci-part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v1
      
    - name: Create zip deploymen packege
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
    - name: Configure my AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_KEY }}
        aws-region : ${{ env.AWS_REGION_NAME }}
        
    - name: Copy deploymen packege to S3 bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{ env.S3_BUCKET_NAME }}/
    
    - name: Print happy message for Ci finish 
      run: echo "Ci Pipeline part finished"
        
